name: stize.dotnet.CI

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      sln: './src/Stize.sln'

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
                   
      - uses: actions/setup-dotnet@v1
        name: setup dotnet
        with:
            dotnet-version: '8.0.x' # SDK Version to use;
            
      - uses: Stelzi79/action-minver@3.0.1
        name: run minver
        id: version        
              
      - name: build
        run: |
            dotnet build ${{ env.sln }}
            
      - name: test
        run: |
            dotnet test ${{ env.sln }}

      - name: pack
        run: |
            dotnet pack ${{ env.sln }} -p:PackageVersion=${{steps.version.outputs.version}}

            
      - name: push private
        run: |
            dotnet nuget add source https://nuget.pkg.github.com/stize/index.json -n github -u stize -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
            until dotnet nuget push "./artifacts/build/*.nupkg" --source "github" --skip-duplicate --no-symbols true; do echo "Retrying"; sleep 1; done