name: stize.dotnet-CD

on:
  push:
    branches: [ feature/publish-github-packages ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      sln: './src/Stize.sln'

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
                   
      - uses: actions/setup-dotnet@v1
        name: setup dotnet
        with:
            dotnet-version: '3.1.x' # SDK Version to use; x will use the latest version of the 3.1 channel
            
      - uses: thefringeninja/action-minver@2.0.0-preview1
        name: run minver
        id: version        
              
      - name: build
        run: |
            dotnet build ${{ env.sln }}
            
      - name: test
        run: |
            dotnet test ${{ env.sln }}

      - name: pack
        run: |
            dotnet pack ${{ env.sln }} -p:PackageVersion=${{MinVerVersion}}

      - name: list
        run: |
            ls ./artifacts/build/*.nupkg
            
      # - name: push private
        # run: |
            # dotnet nuget add source https://nuget.pkg.github.com/stize/index.json -n github -u stize -p ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
            # dotnet nuget push ./artifacts/build/*.nupkg --source "github"